[workspace]
members = ["core", "machine", "nat", "router", "."]

[package]
name = "netsim-embed"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Network simulator."
license = "MIT"
repository = "https://github.com/ipfs-rust/netsim-embed"

[dependencies]
env_logger = "0.7.1"
netsim-embed-core = { version = "0.1.0", path = "core" }
netsim-embed-machine = { version = "0.1.0", path = "machine" }
netsim-embed-nat = { version = "0.1.0", path = "nat" }
netsim-embed-router = { version = "0.1.0", path = "router" }
pnet_packet = "0.26.0"
smol = "0.1.18"
futures = "0.3.5"

[dev-dependencies]
ipfs-embed = "0.2.0"
libipld = { version = "0.3.0", default-features = false }
tempdir = "0.3.7"

[patch.crates-io]
libp2p = { path = "../rust-libp2p" }
ipfs-embed = { path = "../ipfs-embed" }
