[workspace]
members = ["core", "machine", "nat", "router", "."]

[package]
name = "netsim-embed"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
env_logger = "0.7.1"
netsim-embed-core = { path = "core" }
netsim-embed-machine = { path = "machine" }
netsim-embed-nat = { path = "nat" }
netsim-embed-router = { path = "router" }
pnet_packet = "0.26.0"
smol = "0.1.18"
futures = "0.3.5"

[dev-dependencies]
ipfs-embed = "0.1.1"
libipld = { version = "0.3.0", default-features = false }
tempdir = "0.3.7"
