[workspace]
members = ["core", "machine", "nat", "router", "."]

[package]
name = "netsim-embed"
version = "0.1.1"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Network simulator."
license = "MIT"
repository = "https://github.com/ipfs-rust/netsim-embed"

[dependencies]
env_logger = "0.8.3"
netsim-embed-core = { version = "0.1.0", path = "core" }
netsim-embed-machine = { version = "0.1.0", path = "machine" }
netsim-embed-nat = { version = "0.1.0", path = "nat" }
netsim-embed-router = { version = "0.1.0", path = "router" }
pnet_packet = "0.27.2"
smol = "1.2.5"
futures = "0.3.13"
