[package]
name = "smol-netsim-nat"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
log = "0.4.8"
pnet_packet = "0.26.0"
rand = "0.7.3"
smol-netsim-core = { path = "../core" }
