[package]
name = "netsim-embed-core"
version = "0.1.1"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Core types for netsim embed."
license = "MIT"
repository = "https://github.com/ipfs-rust/netsim-embed"

[dependencies]
futures = "0.3.12"
rand = "0.8.2"
thiserror = "1.0.23"
